name: PR Pipeline - CDK + Microservices

on:
  pull_request:
    branches: [main, develop]

jobs:
  build-cdk:
    name: Build CDK Root
    runs-on: ubuntu-latest
    outputs:
      node-version: 18
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (CDK root)
        run: npm install

      - name: Build CDK
        run: npm run build

  build-services:
    name: Build Microservices
    runs-on: ubuntu-latest
    needs: build-cdk

    strategy:
      matrix:
        service:
          - company-service
          - order-service
          - product-service
          - user-service
          - web-portal

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install & Build ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: |
          rm -rf node_modules dist
          npm install
          if [ -f .env.example ]; then cp .env.example .env; fi
          npm run build

  cdk-checks:
    name: CDK Synth & Diff
    runs-on: ubuntu-latest
    needs:
      - build-cdk
      - build-services

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (CDK root)
        run: npm install

      - name: Build CDK
        run: npm run build

      - name: CDK Synth
        run: npx cdk synth

      - name: CDK Diff
        run: npx cdk diff
